import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Sidebar from "@/components/Sidebar";
import Modal from "@/components/Modal";
import { getAllBoards } from "@/data/BoardManager";
import Head from "next/head";

const jakartaSans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const boards = await getAllBoards();

  return (
    <html lang="en" className="dark">
      <head>
        <script
        // dangerouslySetInnerHTML={{
        //   __html: `
        //     (function() {
        //       const savedTheme = localStorage.getItem('theme');
        //       const systemPrefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
        //       if (savedTheme === 'dark' || (!savedTheme && systemPrefersDark)) {
        //         document.documentElement.classList.add('dark');
        //       } else {
        //         document.documentElement.classList.remove('dark');
        //       }
        //     })();
        //   `,
        // }}
        />
      </head>
      <body
        className={`${jakartaSans.className} bg-gray-light dark:bg-black-medium flex h-screen`}
      >
        <Sidebar boards={boards ? boards : []} />
        <div className="flex-1 flex flex-col h-full overflow-hidden">
          <Nav />
          <main className="flex-1 p-5 overflow-hidden">{children}</main>
        </div>
        <Modal />
      </body>
    </html>
  );
}
