import {
  Github,
  Linkedin,
  Code,
  Mail,
  CircleHelp,
  ChevronRight,
  ChevronLeft,
  MoveRight,
  Menu,
  Heart,
  Share,
  AlertCircle,
  ChevronDown,
  Sun,
  Moon,
  LayoutDashboard,
  Plus,
  EyeOff,
  EllipsisVertical,
} from "lucide-react";

export const Icons = {
  linkedIn: Linkedin,
  code: Code,
  mail: Mail,
  question: CircleHelp,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  arrowRight: MoveRight,
  menu: Menu,
  heart: Heart,
  share: Share,
  alertCircle: AlertCircle,
  chevronDown: ChevronDown,
  sun: Sun,
  moon: Moon,
  board: LayoutDashboard,
  plus: Plus,
  hide: EyeOff,
  elipsisVertical: EllipsisVertical,
};
